# Generated by Django 5.2.8 on 2025-11-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_donationarea_donation_gallery_volunteer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='volunter',
            new_name='volunteer',
        ),
        migrations.AlterField(
            model_name='donation',
            name='donationname',
            field=models.CharField(choices=[('Food Donation', 'Food Donation'), ('Cloth Donation', 'Cloth Donation'), ('Footwear Donation', 'Footwear Donation'), ('Books Donation', 'Books Donation'), ('Furniture Donation', 'Furniture Donation'), ('Vessel Donation', 'Vessel Donation'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
